server:
  error:
    whitelabel:
      enabled: false
    path: /error
  port: 8080
  shutdown: graceful

spring:
  application:
    name: hackathon
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  # 자동 재시작 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # 화면 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  # SQL DB
  datasource:
    url: jdbc:sqlserver://team2-db-server.database.windows.net:1433;database=team-db;user=team2@team2-db-server;password=qwaszx!@3;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

# AI AGENT 설정
  ai:
    azure:
      endpoint: https://slihackathon-2025-pt-02.openai.azure.com/
      api-key: 2b06d118ef874578920ed3dbcbb84064
      api-version: 2025-01-01-preview
      agent:
        tnc-agent-id: asst_ZPeTZrqtZhjep5moDv9sJrDh
        product-agent-id: asst_4vF2ALMSNdCW2teeRFfCQB1f
        medical-agent-id: asst_CCfJ53W0waDDmjG7luLGtpdg
        customer-agent-id: asst_ekPy5cKGjnnZrXR4TY8dtLNR

# 로그 설정
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%21.21t] %-5level %40.40c:%4.4L - %m%n"
  level:
    org.springframework: info
    org.apache.hc.client5.http.wire: warn
    org.apache.hc.client5.http: warn
    com.hackathon: debug

